#!/bin/bash

# 读取 commit message
commit_msg=$(cat "$1")

# 定义 commit message 格式规则
pattern="^(revert: )?(feat|fix|docs|style|refactor|perf|test|build|ci|chore)(.+)?: .{1,50}"

if [[ $commit_msg =~ $pattern ]]; then
    # 如果格式正确，脚本将正常退出
    echo "Commit message 格式正确"
    exit 0
else
    echo "Commit message 格式不正确！"
    echo "正确格式应为：<type>(<scope>): <subject>"
    echo "例如：feat(login): add password strength meter"
    exit 1
fi